Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and
create a real matrix product.

Example:
Input:
Enter value M: 5
Enter value N: 3
Enter value A: 2
Output:
First array:

[[0.92825664 0.62790011 0.80130199]
[0.64283876 0.16558409 0.54573802]
[0.04319311 0.80229079 0.72512472]
[0.8005622 0.98844625 0.6982794 ]
[0.46600134 0.51451131 0.6415925 ]]

Second array:

[[0.31898348 0.49050318]
[0.53845583 0.48259499]
[0.89102055 0.35539951]]

Dot product of two arrays:
[[1.34817154 1.04311661]
[0.78047845 0.58917954]
[1.09187707 0.66607684]
[1.40978205 1.11786566]
[0.99736045 0.70489738]]

In [64]:
import numpy as np

M = int(input("Enter value of M"))
N = int(input("Enter value of N"))
A = int(input("Enter value of A"))

mat1= np.random.random((M,N))
print("First array:\n", mat1)

mat2= np.random.random((N,A))
print("Second array:\n", mat2)

mul =np.dot(mat1, mat2)
print("Dot product of two arrays:\n",mul)

Enter value of M 5
Enter value of N 3
Enter value of A 2


First array:
 [[0.27360688 0.10714463 0.3426758 ]
 [0.30849157 0.81669848 0.39053228]
 [0.3408479  0.78063967 0.10750092]
 [0.63321482 0.16726563 0.92035565]
 [0.74978383 0.9065478  0.51058699]]
Second array:
 [[0.0386255  0.0358664 ]
 [0.64233896 0.94593181]
 [0.88341968 0.15911197]]
Dot product of two arrays:
 [[0.38211792 0.16568863]
 [0.8815168  0.84574392]
 [0.60956913 0.76776157]
 [0.94495977 0.32737262]
 [1.06233435 0.96566495]]


Problem Statement 2: Write a NumPy program to check if each element of an array of your
choice is composed of digits, lower case letters, and upper case letters only.
Hint: You can use isdigit(),islower(), and isupper() function.
Example:
 Input: Original Array:
 ['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
 
 Output: Digits only = [False False False False False True]
 Lower cases only = [False False False False True False]
 Upper cases only = [False True True False False False]
 

In [65]:
import numpy as np
arr = np.array(['Python', 'PHP', 'JS', 'Examples' ,'html5', '5'])

digits = [i.isdigit() for i in arr ]
print("Digits only = ", digits)

lower = [i.islower() for i in arr ]
print("Lower cases only = ", lower)

upper = [i.isupper() for i in arr ]
print("Upper cases only = ", upper)

Digits only =  [False, False, False, False, False, True]
Lower cases only =  [False, False, False, False, True, False]
Upper cases only =  [False, True, True, False, False, False]


Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and
𝑌 as input and perform the following tasks:
Tasks to be performed:
1. Create a list (lst1) starting at one (1) with 16 elements at a step of 𝑋
2. Create a list (lst2) starting at one (1) with 16 elements at a step of 𝑌
3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4. Reshape both the NumPy arrays to (4,4)
5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -
np2)
6. Print all the elements of np3 in a single dimension list like the format as shown below:
a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]
Example:
Input:
7 9
Output:
[ 0 -2 -4 -6 -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]

In [55]:
import numpy as np

X,Y= input().split()

list1=[1]
list2 =[1]
su1=1
su2=1
for i in range(15):
    su1=su1+int(X)
    list1.append(su1)

    
for i in range(15):
    su2=su2+int(Y)
    list2.append(su2)

np1 = np.array(list1).reshape(4,4)
np2 = np.array(list2).reshape(4,4)

np3= np1 - np2 

print("Output", np3.flatten())



 7 9


Output [  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of
shape [3 ∗ 3] and perform the following task:
Task to be performed:
Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄).
Example:
Input:
23 56 87 3 6 96 4 6 78
12 34 54 7 2 54 6 2 78
Output:
[[11 22 33]
[-4 4 42]
[-2 4 0]]

In [63]:


P = np.array([int(i) for i in input().split()]).reshape(3,3)
Q = np.array([int(i) for i in input().split()]).reshape(3,3)

print(P-Q)



 23 56 87 3 6 96 4 6 78
 12 34 54 7 2 54 6 2 78


[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
