In [4]:
# no of prime no. within  a range

count = 1

n = int(input())
ls = [2]
for i in range(3, n):
    flag = 0
    for j in range(2,i) :
        if i % j == 0:
            flag = 1
            break
    if flag == 0:
        ls.append(i)
        count += 1

print(f'count : {count}')
print(ls)

 7


count : 3
[2, 3, 5]


In [19]:
# nth prime num

n = int(input())

i = 3
c = 1

while True:
    flag = 0
    for j in range(2,i):
        if i%j == 0:
            flag = 1
            break
    if flag == 0:
        c = c+1
        if c == n:
            break
    i= i+1

print(i)              # 2,3,5,7,11

 5


11


In [11]:
# printing nth fibbo

def fibbo(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibbo(n-2) + fibbo(n-1)

print(fibbo(5-1))

3


In [41]:
a = 0
b = 1

c = 2
ls = [a,b ]
n = int(input())

while  n > c:
    d = a+b
    ls.append(d)
    
    a = b
    b= d
    c = c+1
print(d)
print(ls)



 7


8
[0, 1, 1, 2, 3, 5, 8]


In [32]:
# cumelative sum

def suma(n):        
    if len(str(n)) == 1:
        return n

    return suma(sum([int(i) for i in str(n)]))

print(suma(123456))
        

3


In [33]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [34]:
arr *5

array([ 5, 10, 15, 20, 25])

In [35]:
arr **2

array([ 1,  4,  9, 16, 25])

In [36]:
a=[1, 3]
a*2

[1, 3, 1, 3]

In [42]:
import numpy as np

arr = np.array([41, 42, 43, 44])
ms = (arr % 2 == 0)
newarr = arr[ms]

print(newarr)

[42 44]


In [5]:
# 1. Write a Python function to rotate a list to the right by k steps.
# Input: [1, 2, 3, 4, 5], k=2
# Output: [4, 5, 1, 2, 3]

def rotete(n, k):
    while k > 0:
        new = n.pop()
        n.insert(0,new)
        k = k-1
    return n

print(rotete([1,2,3,4,5],2))
    

[4, 5, 1, 2, 3]


In [8]:
# 2. Given a string, return the first non-repeating character.
# Input: "swiss"
# Output: 'w'

def nonrep(n):
    for i in n:
        if n.count(i) == 1:
            return i
            break
print(nonrep("swiss"))

w


In [10]:
# 3. Write a Python program to count the frequency of words in a string.
# Input: "hello world hello"
# Output: {'hello': 2, 'world': 1}

def cou(n):
    n = n.split()
    ans = {}
    for i in n:
        if i in ans:
            ans[i] = ans[i] +1
        else:
            ans[i] = 1
    return ans

print(cou("hello world hello"))
        

{'hello': 2, 'world': 1}


In [ ]:
# 4. Write Python code to read a file line by line and count the number of lines that contain the word "error".

# def count_error_lines(file_path):
#     error_count = 0
#     with open(file_path, "r", encoding="utf-8") as file:
#         for line in file:
#             if "error" in line.lower():  # Case-insensitive search
#                 error_count += 1
#     return error_count

# # Example usage
# file_path = "logfile.txt"  # Replace with your file path
# error_lines = count_error_lines(file_path)
# print(f"Number of lines containing 'error': {error_lines}")

In [16]:
# 6. Generate a list of all numbers divisible by 3 and 5 between 1 and 100.
import numpy as np
ar = np.array([i for i in range(101)])

mas = (ar%3 == 0)
ss = (ar % 5 ==0 )

print(ar[mas & ss])

[ 0 15 30 45 60 75 90]


In [17]:
for i in range(101):
    if i%3 == 0 and i%5 ==0:
        print(i)

0
15
30
45
60
75
90


In [27]:
# 7. Given a list of tuples, sort them by the second value in descending order.
Input= [(1, 3), (2, 1), (4, 2)]
# Output: [(1, 3), (4, 2), (2, 1)]

def sortt(n):
    ind = [i[-1] for i in n]
    # print(ind)
    ab = sorted(ind)[::-1]
    # print(ab)
    fil = [ind.index(i) for i in ab]
    ans = []
    for i in fil:
        ans.append(n[i])
    return ans

print(sortt(Input))
    

[(1, 3), (4, 2), (2, 1)]


In [29]:
# Input list of tuples
data = [(1, 3), (2, 1), (4, 2)]

# Sorting based on the second element in descending order
sorted_data = sorted(data, key=lambda x: x[1], reverse=True)
sorted_data

[(1, 3), (4, 2), (2, 1)]

In [ ]:
# 8. Write a Python program to extract all email addresses from a given text.

# import re

# def extract_emails(text):
#     # Regular expression pattern for extracting email addresses
#     email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    
#     # Find all email addresses in the text
#     emails = re.findall(email_pattern, text)
    
#     return emails

In [35]:
def flatten_list(nested_list):
    flat_list = []
    for item in nested_list:
        if isinstance(item, list):  # Check if item is a list
            flat_list.extend(flatten_list(item))  # Recursively flatten
        else:
            flat_list.append(item)
    return flat_list

# Example usage
nested_list = [[1, 2], [3, 4, [5, 6]], 7]
flattened = flatten_list(nested_list)
print(flattened)


[1, 2, 3, 4, 5, 6, 7]


In [36]:
# 10. Flatten a nested list into a single list.
Input = [[1, 2], [3, 4, [5, 6]], 7]
# Output: [1, 2, 3, 4, 5, 6, 7]

def flat_list(Input1):
    ans =[]
    for i in Input1:
        if isinstance(i, list):
            ans.extend(flat_list(i))
        else:
            ans.append(i)
    return ans

print(flat_list(Input))

[1, 2, 3, 4, 5, 6, 7]


In [40]:
def pal(n, k):
    if k > len(n)/2:
        return
    if n[k] == n[len(n)-k-1]:
        pal(n,k+1)

    else:
        return False
    return True

pal("varun",0)
        

False