In [ ]:
# no of prime no. within  a range
count = 1

n = int(input())
ls = [2]
for i in range(3, n):
    flag = 0
    for j in range(2,i) :
        if i % j == 0:
            flag = 1
            break
    if flag == 0:
        ls.append(i)
        count += 1

print(f'count : {count}')
print(ls)


 7


count : 3
[2, 3, 5]


In [19]:
# nth prime num

n = int(input())

i = 3
c = 1

while True:
    flag = 0
    for j in range(2,i):
        if i%j == 0:
            flag = 1
            break
    if flag == 0:
        c = c+1
        if c == n:
            break
    i= i+1

print(i)              # 2,3,5,7,11

 5


11


In [11]:
# printing nth fibbo

def fibbo(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibbo(n-2) + fibbo(n-1)

print(fibbo(5-1))

3


In [41]:
a = 0
b = 1

c = 2
ls = [a,b ]
n = int(input())

while  n > c:
    d = a+b
    ls.append(d)
    
    a = b
    b= d
    c = c+1
print(d)
print(ls)



 7


8
[0, 1, 1, 2, 3, 5, 8]


In [32]:
# cumelative sum

def suma(n):        
    if len(str(n)) == 1:
        return n

    return suma(sum([int(i) for i in str(n)]))

print(suma(123456))
        

3


In [33]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [34]:
arr *5

array([ 5, 10, 15, 20, 25])

In [35]:
arr **2

array([ 1,  4,  9, 16, 25])

In [36]:
a=[1, 3]
a*2

[1, 3, 1, 3]

In [42]:
import numpy as np

arr = np.array([41, 42, 43, 44])
ms = (arr % 2 == 0)
newarr = arr[ms]

print(newarr)

[42 44]


In [5]:
# 1. Write a Python function to rotate a list to the right by k steps.
# Input: [1, 2, 3, 4, 5], k=2
# Output: [4, 5, 1, 2, 3]

def rotete(n, k):
    while k > 0:
        new = n.pop()
        n.insert(0,new)
        k = k-1
    return n

print(rotete([1,2,3,4,5],2))
    

[4, 5, 1, 2, 3]


In [8]:
# 2. Given a string, return the first non-repeating character.
# Input: "swiss"
# Output: 'w'

def nonrep(n):
    for i in n:
        if n.count(i) == 1:
            return i
            break
print(nonrep("swiss"))

w


In [10]:
# 3. Write a Python program to count the frequency of words in a string.
# Input: "hello world hello"
# Output: {'hello': 2, 'world': 1}

def cou(n):
    n = n.split()
    ans = {}
    for i in n:
        if i in ans:
            ans[i] = ans[i] +1
        else:
            ans[i] = 1
    return ans

print(cou("hello world hello"))
        

{'hello': 2, 'world': 1}


In [ ]:
# 4. Write Python code to read a file line by line and count the number of lines that contain the word "error".

# def count_error_lines(file_path):
#     error_count = 0
#     with open(file_path, "r", encoding="utf-8") as file:
#         for line in file:
#             if "error" in line.lower():  # Case-insensitive search
#                 error_count += 1
#     return error_count

# # Example usage
# file_path = "logfile.txt"  # Replace with your file path
# error_lines = count_error_lines(file_path)
# print(f"Number of lines containing 'error': {error_lines}")

In [16]:
# 6. Generate a list of all numbers divisible by 3 and 5 between 1 and 100.
import numpy as np
ar = np.array([i for i in range(101)])

mas = (ar%3 == 0)
ss = (ar % 5 ==0 )

print(ar[mas & ss])

[ 0 15 30 45 60 75 90]


In [17]:
for i in range(101):
    if i%3 == 0 and i%5 ==0:
        print(i)

0
15
30
45
60
75
90


In [27]:
# 7. Given a list of tuples, sort them by the second value in descending order.
Input= [(1, 3), (2, 1), (4, 2)]
# Output: [(1, 3), (4, 2), (2, 1)]

def sortt(n):
    ind = [i[-1] for i in n]
    # print(ind)
    ab = sorted(ind)[::-1]
    # print(ab)
    fil = [ind.index(i) for i in ab]
    ans = []
    for i in fil:
        ans.append(n[i])
    return ans

print(sortt(Input))
    

[(1, 3), (4, 2), (2, 1)]


In [29]:
# Input list of tuples
data = [(1, 3), (2, 1), (4, 2)]

# Sorting based on the second element in descending order
sorted_data = sorted(data, key=lambda x: x[1], reverse=True)
sorted_data

[(1, 3), (4, 2), (2, 1)]

In [ ]:
# 8. Write a Python program to extract all email addresses from a given text.

# import re

# def extract_emails(text):
#     # Regular expression pattern for extracting email addresses
#     email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    
#     # Find all email addresses in the text
#     emails = re.findall(email_pattern, text)
    
#     return emails

In [35]:
def flatten_list(nested_list):
    flat_list = []
    for item in nested_list:
        if isinstance(item, list):  # Check if item is a list
            flat_list.extend(flatten_list(item))  # Recursively flatten
        else:
            flat_list.append(item)
    return flat_list

# Example usage
nested_list = [[1, 2], [3, 4, [5, 6]], 7]
flattened = flatten_list(nested_list)
print(flattened)


[1, 2, 3, 4, 5, 6, 7]


In [36]:
# 10. Flatten a nested list into a single list.
Input = [[1, 2], [3, 4, [5, 6]], 7]
# Output: [1, 2, 3, 4, 5, 6, 7]

def flat_list(Input1):
    ans =[]
    for i in Input1:
        if isinstance(i, list):
            ans.extend(flat_list(i))
        else:
            ans.append(i)
    return ans

print(flat_list(Input))

[1, 2, 3, 4, 5, 6, 7]


In [40]:
def pal(n, k):
    if k > len(n)/2:
        return
    if n[k] == n[len(n)-k-1]:
        pal(n,k+1)

    else:
        return False
    return True

pal("varun",0)
        

False

In [47]:
#selection sort

a = [4,7,2,8,5]

for i in range(len(a)):
    mina = i
    for j in range(i+1, len(a)):
        if a[mina] > a[j]:
            mina = j
    (a[mina] , a[i]) = (a[i] , a[mina])

print(a)

[2, 4, 5, 7, 8]


In [50]:
# bubble sort
a = [4,7,2,8,5]

l = len(a)
swapped = 1
while l > 0:
    for i in range(l-1):
        if a[i] > a[i+1]:
            swapped = 0
            (a[i], a[i+1]) = (a[i+1], a[i])
    if swapped == 1:
        break
    l =l-1
print(a)


[2, 4, 5, 7, 8]


In [52]:
# insertion sort
a = [4,7,2,8,5]
l = len(a)

for i in range(1,l):
    key = a[i]
    j = i-1
    while j>=0 and a[j] > key:
        a[j+1] = a[j]
        j =j-1
    a[j+1] = key

print(a)

[2, 4, 5, 7, 8]


In [2]:
#merge sort

a = [4,7,2,8,5]

def merge_sort(a):
    if len(a) <= 1:
        return a

    mid = len(a)//2
    left_sort = merge_sort(a[:mid])
    right_sort = merge_sort(a[mid:])

    return merge(left_sort, right_sort)

def merge(l , r):
    res = []
    c, d = 0, 0

    while c < len(l) and d < len(r):
        if l[c] < r[d]:
            res.append(l[c])
            c =c+1
        else:
            res.append(r[d])
            d =d+1

    res.extend(l[c:])
    res.extend(r[d:])

    return res

print(merge_sort(a))

[2, 4, 5, 7, 8]


In [6]:
#selecti

a = [3,5,2,6,53,6]

for i in range(len(a)):
    mina = i
    for j in range(i, len(a)):
        if a[mina] > a[j]:
            print(j)
            mina =j

    (a[mina] , a[i]) = (a[i], a[mina])
    

print(a)

2
2
5
[2, 3, 5, 6, 6, 53]


In [58]:
# bb
a = [3,5,2,6,53,6]

l = len(a)

while l>0:
    for i in range(l-1):
        if a[i] > a[i+1]:
            (a[i], a[i+1]) = (a[i+1],a[i])

    l = l-1

print(a)


[2, 3, 5, 6, 6, 53]


In [61]:
# linear serch

a = [3,4,12,33,14,21]
key = 1

for i in range(len(a)):
    if a[i] == key:
        print(i)
        break
if i ==len(a)-1:
    print("not fount")

not fount


In [10]:
# Binary Search in python


def binarySearch(array, x, low, high):

    if high >= low:

        mid = low + (high - low)//2

        # If found at mid, then return it
        if x == array[mid]:
            return mid

        # Search the right half
        elif x > array[mid]:
            return binarySearch(array, x, mid + 1, high)

        # Search the left half
        else:
            return binarySearch(array, x, low, mid - 1)

    else:
        return -1


array = [3, 4, 5, 6, 7, 8, 9]
x = 4

result = binarySearch(array, x, 0, len(array)-1)

if result != -1:
    print("Element is present at index " + str(result))
else:
    print("Not found")
    

Element is present at index 1


In [9]:
# Binary Search in python


def binarySearch(array, x, low, high):

    # Repeat until the pointers low and high meet each other
    while low <= high:

        mid = low + (high - low)//2

        if x == array[mid]:
            return mid

        elif x > array[mid]:
            low = mid + 1

        else:
            high = mid - 1

    return -1


array = [3, 4, 5, 6, 7, 8, 9]
x = 4

result = binarySearch(array, x, 0, len(array)-1)

if result != -1:
    print("Element is present at index " + str(result))
else:
    print("Not found")

Element is present at index 1
